version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.26
    - 14.14.30
    - 14.14.34
    - 14.14.35
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.19.0
  - dependency-name: homebridge
    versions:
    - 1.3.0
    - 1.3.1
    - 1.3.4
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: hap-nodejs
    versions:
    - 0.9.0
  - dependency-name: esphome-ts
    versions:
    - 3.0.5
